spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: accounts-service
        uri: http://localhost:8081
        predicates:
        - Path=/api/v1/accounts/**
server:
  port: 8089
