spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: accounts-service
          uri: http://localhost:8081
          predicates:
          - Path=/api/v1/accounts/**
  main:
    web-application-type: reactive
server:
  port: 8089
